import type { HybridObject } from "react-native-nitro-modules";

/**
 * A native background timer module that works when the app is backgrounded.
 * Uses DispatchSourceTimer for efficient, RunLoop-free timer execution.
 *
 * Features smart power management:
 * - Automatically adjusts timer leeway based on app state (foreground/background)
 * - Scales leeway with interval duration for optimal power efficiency
 * - Allows manual leeway override for precise control
 */
export interface Timer
  extends HybridObject<{ ios: "swift"; android: "kotlin" }> {
  /**
   * Schedules a one-shot timer that fires after the specified delay.
   *
   * @param id - Unique timer ID (generated by JS side)
   * @param delayMs - Delay in milliseconds before the callback fires
   * @param callback - Function to call when timer fires, receives the timer ID
   * @param leewayMs - Optional leeway in milliseconds for power efficiency.
   *                   Use -1 (default) for automatic leeway based on app state and delay.
   *                   Use 0 for precise timing (higher power consumption).
   */
  setTimeout(
    id: number,
    delayMs: number,
    callback: (id: number) => void,
    leewayMs: number,
  ): void;

  /**
   * Cancels a previously scheduled timeout.
   * Safe to call with an invalid or already-fired ID.
   *
   * @param id - The timer ID to cancel
   */
  clearTimeout(id: number): void;

  /**
   * Schedules a repeating timer that fires at the specified interval.
   *
   * @param id - Unique timer ID (generated by JS side)
   * @param intervalMs - Interval in milliseconds between callback invocations
   * @param callback - Function to call on each interval, receives the timer ID
   * @param leewayMs - Optional leeway in milliseconds for power efficiency.
   *                   Use -1 (default) for automatic leeway based on app state and interval.
   *                   Use 0 for precise timing (higher power consumption).
   */
  setInterval(
    id: number,
    intervalMs: number,
    callback: (id: number) => void,
    leewayMs: number,
  ): void;

  /**
   * Cancels a previously scheduled interval.
   * Safe to call with an invalid or already-cleared ID.
   *
   * @param id - The interval ID to cancel
   */
  clearInterval(id: number): void;
}
